version: '3'
services:

  db:
    image: mysql:5.7
    env_file: ./dockerfiles/.env
    ports:
      - "3307:3306"
    volumes:
      - mysql-db:/var/lib/mysql

  redis:
    image: redis:latest
    environment:
      - TZ=Asia/Almaty
    ports:
      - "6380:6379"

  web:
    build: ./
    env_file: ./dockerfiles/.env
    working_dir: /var/www/app
    command: bash -c "/docker-entrypoint.sh"
    volumes:
      - ./:/var/www/app
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    ports:
      - "8000:8000"

  celery:
    build: ./
    working_dir: /var/www/app
    command: bash -c "celery -A trigger worker -c 4 -B"
    volumes:
      - ./:/var/www/app
    depends_on:
      - web
    links:
      - db
      - redis

volumes:
  mysql-db: